version: '3'
services:
  register-api:
    container_name: register-api
    image: udomiljubimca/register-api:1.0
    environment:
        - FLASK_ENV=${FLASK_ENV}
        - KYECLOAK_ADMIN_USER=${KYECLOAK_ADMIN_USER}
        - KYECLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD_DEV}
        - CLIENT_RELM_SECRET=${CLIENT_RELM_SECRET}
        - CLIENT_RELM_NAME=${CLIENT_RELM_NAME}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_CLIENT_NAME=${KEYCLOAK_CLIENT_NAME}
    ports:
    - 8080
networks:
  udomiljubimca_dev:
    driver: bridge