version: '3'
services:
  register-api:
    container_name: register-api
    image: udomiljubimca/register-api:1.0
    environment:
        - FLASK_ENV: ${FLASK_ENV}
        - KYECLOAK_ADMIN_USER: ${KEYCLOAK_PASSWORD_DEV}
        - KYECLOAK_ADMIN_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        - CLIENT_RELM_SECRET : ${CLIENT_RELM_SECRET}
        - CLIENT_RELM_NAME: ${CLIENT_RELM_NAME}
    ports:
    - "10.123.176.2:8081:8080"
    networks:
    - udomiljubimca_dev
networks:
  udomiljubimca_dev:
    driver: bridge