version: '3'
services:
  register-api:
    container_name: register-api
    image: udomiljubimca/register-api:1.1
    environment:
        - FLASK_ENV=${FLASK_ENV}
        - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
        - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD_DEV}
        - CLIENT_RELM_SECRET=${CLIENT_RELM_SECRET}
        - CLIENT_RELM_NAME=${CLIENT_RELM_NAME}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_CLIENT_NAME=${KEYCLOAK_CLIENT_NAME}
    networks:
    - udomiljubimca_monitoring
  auth-api:
    container_name: auth-api
    image: udomiljubimca/auth-api:1.1
    environment:
        - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
        - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD_DEV}
        - CLIENT_RELM_SECRET=${CLIENT_RELM_SECRET}
        - CLIENT_RELM_NAME=${CLIENT_RELM_NAME}
        - KEYCLOAK_URL_WITH_PATH=${KEYCLOAK_URL_WITH_PATH}
    networks:
    - udomiljubimca_monitoring
networks:
  udomiljubimca_monitoring:
    driver: bridge
