version: '3'
volumes:
  grafana_data: {}
  kong-datastore: {}
  prometheus_data: {}
  postgres_keycloak_data_dev:
      driver: local
services:
  postgres:
    container_name: keycloka-postgres-dev
    image: postgres
    volumes:
      - postgres_keycloak_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
    - udomiljubimca_monitoring
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloka-postgres-dev
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KYECLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD_DEV}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
    - udomiljubimca_monitoring
  # nginx-proxy:
  #   container_name: nginx-gateway-dev
  #   build:
  #     context: ./nginx-proxy
  #   ports:
  #   - 80:80
  #   networks:
  #   - udomiljubimca_monitoring

  # kong-db:
  #   image: postgres:9.6
  #   container_name: kong-db
  #   volumes:
  #     - kong-datastore:/var/lib/postgresql/data
  #   networks:
  #     - udomiljubimca_monitoring
  #   environment:
  #     POSTGRES_DB: api-gw
  #     POSTGRES_USER: kong
  #     #POSTGRES_PASSWORD: 
  #     POSTGRES_HOST_AUTH_METHOD: trust

  # kong:
  #   container_name: kong
  #   build:
  #     context: ./kong
  #   depends_on:
  #     - kong-db
  #   networks:
  #     - udomiljubimca_monitoring
  #   ports:
  #     - "8000:8000" # Listener
  #     - "8001:8001" # Admin API
  #     # - "8443:8443" # Listener  (SSL)
  #     # - "8444:8444" # Admin API (SSL)
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-db
  #     KONG_PG_PORT: 5432
  #     KONG_PG_DATABASE: api-gw
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_PROXY_LISTEN: 0.0.0.0:8000
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #     KONG_PLUGINS: oidc

  ##### prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "10.123.176.2:9090:9090"
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - udomiljubimca_monitoring
  ##### nodeexporter
  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "10.123.176.2:9100:9100"
    depends_on:
      - prometheus
    networks:
      - udomiljubimca_monitoring
  ##### grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "10.123.176.2:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - udomiljubimca_monitoring
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    volumes:
      - ./monitoring/blackbox-config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped
    ports:
      - "10.123.176.2:9115:9115"
    networks:
      - udomiljubimca_monitoring
networks:
  udomiljubimca_monitoring:
    driver: bridge