global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'udomiljubimca-dev-machine'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: monitoring-blackbox # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:9115

  # - job_name: 'monitoring-http-staging-auth'
  #   metrics_path: /probe
  #   params:
  #     module: [http_get_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #       - http://10.122.230.31:8080/api/v1/register/health-check    # Target to probe with http.
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: 10.122.230.39:9115  # The blackbox exporter's real hostname:port.
  #     - source_labels:
  #       - module
  #       target_label: __param_modul
